### ISSUE TITLE
DSharpPlus 5.0.0 support

### ISSUE THREAD

**Issue by sowa705** [nefarius/Nefarius.DSharpPlus.Extensions.Hosting#177]
Hi, what is the support status for 5.0.0 nightlies? I am unable to use these packages after upgrading to 5.0.0 because of 
 `System.TypeLoadException: Could not load type 'DSharpPlus.EventArgs.ReadyEventArgs' from assembly 'DSharpPlus, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'`

**Comment by nefarius** [comment]
That is a very good question; should probably make some releases for them, thanks for reminding!

**Comment by nefarius** [comment]
Hm, so sadly just updating to the nightly packages is not enough; there have been some breaking changes I need to figure out first:

![image](https://github.com/nefarius/Nefarius.DSharpPlus.Extensions.Hosting/assets/286631/9890c794-7617-4aad-ac41-a21d253238e2)

**Comment by sowa705** [comment]
Yeah, there were some API changes, I'll wait on 4.4.2 until this repo gets updated, It's been very useful for me :)

**Comment by nefarius** [comment]
Glad to hear! Shouldn't be a ton of work, just adjusting the source generators to whatever breaking change occurred.

**Comment by nefarius** [comment]
Gonna do a 4.4.3 release in between next.

**Comment by nefarius** [comment]
Published a new NuGet with changes from #188 

I couldn't get GitVersion to work the way I envisioned so it's not a pre-release. Oh well, stupid computers...
